-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "estimatedCostUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "inputTokens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "outputTokens" INTEGER NOT NULL DEFAULT 0;
