import { query } from "@anthropic-ai/claude-agent-sdk";
import { prisma } from "../db.js";
import { simpleGit } from "simple-git";
import { cloneOrPullRepo, createWorktree, cleanupWorktree } from "../services/repo-manager.js";
import { createPullRequest } from "./pr-creator.js";
import { config } from "../config.js";
import { decrypt } from "@autosoftware/shared";

async function resolveApiKey(userId: string): Promise<{ key: string; apiKeyId: string | null }> {
  if (config.apiKeyEncryptionSecret) {
    const dbKey = await prisma.apiKey.findFirst({
      where: { userId, isActive: true },
      orderBy: { priority: "asc" },
    });
    if (dbKey) {
      try {
        const plainKey = decrypt(dbKey.encryptedKey, config.apiKeyEncryptionSecret);
        return { key: plainKey, apiKeyId: dbKey.id };
      } catch {
        // Decryption failed, fall through
      }
    }
  }
  return { key: config.anthropicApiKey, apiKeyId: null };
}

export async function handleTaskExecution(jobs: { data: { taskId: string } }[]) {
  const job = jobs[0];
  const { taskId } = job.data;
  console.log(`Starting execution for task ${taskId}`);

  const task = await prisma.task.findUnique({
    where: { id: taskId },
    include: {
      repository: {
        include: {
          user: { include: { accounts: true } },
        },
      },
    },
  });

  if (!task || task.status === "cancelled") {
    console.log(`Task ${taskId} not found or cancelled`);
    return;
  }

  const repo = task.repository;

  // Resolve API key from DB or env
  const { key: resolvedKey, apiKeyId } = await resolveApiKey(repo.userId);

  if (!resolvedKey || resolvedKey === "sk-ant-xxx") {
    await prisma.task.update({
      where: { id: taskId },
      data: {
        status: "failed",
        metadata: { error: "No API key available. Add one in Settings or set ANTHROPIC_API_KEY in .env." },
      },
    });
    console.error("Task aborted: No API key available");
    return;
  }

  // Set env for Agent SDK
  process.env.ANTHROPIC_API_KEY = resolvedKey;

  const account = repo.user.accounts.find((a: any) => a.provider === repo.provider);
  if (!account) {
    await prisma.task.update({
      where: { id: taskId },
      data: {
        status: "failed",
        metadata: { error: `No OAuth account found for provider ${repo.provider}` },
      },
    });
    return;
  }

  await prisma.task.update({
    where: { id: taskId },
    data: { status: "in_progress" },
  });

  const branchName = `autosoftware/${task.type}/${taskId.slice(0, 8)}`;
  let worktreeDir: string | null = null;
  let repoDir: string | null = null;

  try {
    repoDir = await cloneOrPullRepo(repo.id, repo.cloneUrl, account.accessToken, repo.provider);
    worktreeDir = await createWorktree(repoDir, branchName);

    let resultText = "";
    let sessionId: string | undefined;

    for await (const message of query({
      prompt: `You are an expert software engineer. Implement the following task:

## Task: ${task.title}

${task.description}

## Instructions:
1. Read relevant files to understand the codebase
2. Plan your changes carefully
3. Implement the changes with clean code
4. Run existing tests to verify nothing breaks
5. Add tests for new functionality if applicable
6. Commit with a clear message

## Rules:
- Follow existing code style
- Don't break existing functionality
- Write clean, readable code`,
      options: {
        allowedTools: [
          "Read", "Edit", "Write", "Bash", "Glob", "Grep",
          "WebSearch", "WebFetch", "Agent",
        ],
        permissionMode: "bypassPermissions",
        maxTurns: 60,
        maxBudgetUsd: config.defaultTaskBudget,
        cwd: worktreeDir,
      },
    })) {
      if (message.type === "system" && message.subtype === "init") {
        sessionId = message.session_id;
      }
      if (message.type === "result") {
        if (message.subtype === "success") {
          resultText = message.result;
        } else {
          throw new Error(`Agent stopped: ${message.subtype}`);
        }
      }
    }

    const git = simpleGit(worktreeDir);
    const log = await git.log({ maxCount: 5 });

    if (log.total === 0) {
      throw new Error("Agent did not make any commits");
    }

    await git.push("origin", branchName, ["--set-upstream"]);

    const pr = await createPullRequest(
      repo.provider,
      account.accessToken,
      repo.fullName,
      {
        title: `[AutoSoftware] ${task.title}`,
        body: `## Automated Changes\n\n${task.description}\n\n---\n\n### Agent Summary\n\n${resultText}\n\n---\n*Generated by AutoSoftware*`,
        head: branchName,
        base: repo.defaultBranch,
      }
    );

    await prisma.task.update({
      where: { id: taskId },
      data: {
        status: "completed",
        completedAt: new Date(),
        pullRequestUrl: pr.url,
        pullRequestStatus: "open",
        agentSessionId: sessionId,
        metadata: {
          resultSummary: resultText,
          branch: branchName,
          commits: log.all.map((c) => ({ hash: c.hash, message: c.message })),
        },
      },
    });

    // Record usage if using a DB key
    if (apiKeyId) {
      await prisma.apiKeyUsage.create({
        data: {
          apiKeyId,
          model: "claude-sonnet-4-20250514",
          inputTokens: 0,
          outputTokens: 0,
          estimatedCostUsd: 0,
          source: "task",
          sourceId: taskId,
        },
      });
      await prisma.apiKey.update({
        where: { id: apiKeyId },
        data: { lastUsedAt: new Date(), lastError: null },
      });
    }

    console.log(`Task ${taskId} completed. PR: ${pr.url}`);
  } catch (err) {
    console.error(`Task ${taskId} failed:`, err);

    if (apiKeyId) {
      await prisma.apiKey.update({
        where: { id: apiKeyId },
        data: { lastError: err instanceof Error ? err.message : "Unknown error" },
      }).catch(() => {});
    }

    await prisma.task.update({
      where: { id: taskId },
      data: {
        status: "failed",
        metadata: {
          error: err instanceof Error ? err.message : "Unknown error",
          branch: branchName,
        },
      },
    });

    throw err;
  } finally {
    if (repoDir && worktreeDir) {
      await cleanupWorktree(repoDir, worktreeDir).catch(() => {});
    }
  }
}
