/**
 * Project memory helpers for the worker:
 * - Auto-create memories from completed tasks
 * - Retrieve relevant memories for task execution context
 */

import { prisma } from "../db.js";
import { simpleQuery } from "./claude-query.js";

/**
 * Fetch memories relevant to a task and format them as prompt context.
 * Returns an empty string if no memories are found.
 */
export async function getMemoryContext(
  userId: string,
  repositoryId: string,
  projectId: string | null,
  task: { title: string; description: string | null; type: string; affectedFiles?: string[] }
): Promise<string> {
  // Fetch memories for this repository (and project if available)
  const where: any = {
    userId,
    repositoryId,
    isConsolidated: false,
  };

  const memories = await prisma.projectMemory.findMany({
    where,
    orderBy: { importance: "desc" },
    take: 15,
    select: {
      category: true,
      title: true,
      content: true,
      importance: true,
      tags: true,
    },
  });

  if (memories.length === 0) return "";

  // Simple keyword relevance scoring against task context
  const taskText = `${task.title} ${task.description || ""} ${task.type} ${(task.affectedFiles || []).join(" ")}`.toLowerCase();
  const scored = memories.map((m) => {
    const words = `${m.title} ${m.content} ${(m.tags as string[]).join(" ")}`.toLowerCase().split(/\s+/);
    const matchCount = words.filter((w) => w.length > 3 && taskText.includes(w)).length;
    return { ...m, relevance: matchCount + m.importance };
  });

  scored.sort((a, b) => b.relevance - a.relevance);
  const top = scored.slice(0, 8);

  if (top.length === 0) return "";

  const lines = top.map(
    (m) => `- [${m.category}, importance: ${m.importance}/10] ${m.title}: ${m.content}`
  );

  return `## Project Memory (past learnings for this repository)
The following are relevant learnings and decisions from previous tasks on this repository. Use them to inform your approach:

${lines.join("\n")}

---

`;
}

export async function createMemoryFromTask(
  userId: string,
  taskId: string
): Promise<void> {
  const task = await prisma.task.findFirst({
    where: { id: taskId, userId },
    include: {
      repository: { select: { fullName: true } },
    },
  });

  if (!task || task.status !== "completed") return;

  // Only create memory for tasks with enhanced plans or PRs
  if (!task.enhancedPlan && !task.pullRequestUrl) return;

  const affectedFiles = (task.affectedFiles as string[]) ?? [];
  const hasSignificantChanges =
    affectedFiles.length >= 3 ||
    (task.enhancedPlan && task.enhancedPlan.length >= 500) ||
    task.pullRequestUrl;

  if (!hasSignificantChanges) return;

  // Avoid duplicates — skip if a memory already exists for this task
  const existing = await prisma.projectMemory.findFirst({
    where: {
      userId,
      metadata: { path: ["sourceTaskId"], equals: taskId },
    },
  });
  if (existing) return;

  const metadata = (task.metadata as Record<string, unknown>) || {};

  const systemPrompt = `You are extracting learnings from a completed task for future reference.
Create a concise memory entry that captures:
1. What was done
2. Key decisions made
3. Any patterns or approaches that worked well

Respond with JSON only:
{
  "title": "Short descriptive title",
  "content": "Key learnings and decisions",
  "category": "architecture|convention|decision|learning|context",
  "importance": 1-10,
  "tags": ["tag1", "tag2"]
}`;

  const taskContext = [
    `Task: ${task.title}`,
    `Type: ${task.type}`,
    task.description ? `Description: ${task.description}` : "",
    task.enhancedPlan ? `Plan:\n${task.enhancedPlan}` : "",
    metadata.resultSummary ? `Result: ${metadata.resultSummary}` : "",
  ]
    .filter(Boolean)
    .join("\n");

  const { result } = await simpleQuery(
    systemPrompt,
    `Extract learnings from:\n${taskContext}`,
    { model: "claude-sonnet-4-20250514" }
  );

  const jsonMatch = result.match(/\{[\s\S]*\}/);
  if (!jsonMatch) return;

  const parsed = JSON.parse(jsonMatch[0]);

  await prisma.projectMemory.create({
    data: {
      userId,
      projectId: task.projectId || undefined,
      repositoryId: task.repositoryId,
      category: parsed.category || "learning",
      title: parsed.title || task.title,
      content: parsed.content || "",
      importance: parsed.importance ?? 5,
      tags: parsed.tags ?? [],
      relatedTaskIds: [taskId],
      isConsolidated: false,
      sourceMemoryIds: [],
      metadata: {
        sourceTaskId: taskId,
        sourceTaskTitle: task.title,
        autoGenerated: true,
      },
    },
  });

  console.log(`Memory auto-created for task ${taskId}`);
}
